# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-13 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import muzisystem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=250)),
                ('album_releasedate', models.DateField(default=datetime.date.today)),
                ('album_thumbnail', models.FileField(upload_to=muzisystem.models.url_album_thumbnail)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=250)),
                ('artist_description', models.CharField(max_length=1000)),
                ('artist_picture', models.ImageField(upload_to=muzisystem.models.url_artist)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=250)),
                ('genre_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=250)),
                ('track_thumbnail', models.ImageField(blank=True, upload_to=muzisystem.models.url_track_thumbnail)),
                ('track', models.FileField(upload_to=muzisystem.models.url_track)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzisystem.Albums')),
            ],
        ),
        migrations.AddField(
            model_name='albums',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzisystem.Artists'),
        ),
        migrations.AddField(
            model_name='albums',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzisystem.Genre'),
        ),
    ]
